print("Write your name: ")
name = input()
print("\nWelcome,", name + "!")
number_of_letters = len(name)
print("\nTotal number of letters in your name:", number_of_letters, ";")
letter_a_occurrence = name.count("a")
print("Letter 'a' occurrence:", letter_a_occurrence, ".")
