print("Write your name: ")
name = input()
name_upper = name.upper()
print("\nWelcome,", name_upper + "!")
number_of_letters = len(name)
print("\nTotal number of letters in your name:", number_of_letters, ";")
letter_a_occurrence = name_upper.count("A")
print("Letter 'a' occurrence:", letter_a_occurrence, ".")
