print("Write a word that contains at least 5 letters:")
word = input()
print("\nIndex -4:", word[-4])
print("\nSlicing -4 to -1:", word[-4:-1])
print("\nSlicing -5 to 5:", word[-5:5])
print("\nNow write a text containing at least 10 words with no punctuation and press 'Enter'")
text = input()
split = text.split(" ")
print("\n 3rd word:", split[2])
print("\n 7th word:", split[6])
print("\nFirst 3 words:", split[:3])
print("\nLast 5 words:", split[-5:])
print("\nThank you for participating!")

